### ISSUE TITLE
train_scripts/causal_qformer.sh not working

### ISSUE THREAD

**Issue by shubhamgarg21** [AILab-CVC/SEED#30]
Hi,

While trying to run step 3 of Training SEED Tokenization, I am observing following error:

```
Traceback (most recent call last):
  File "/SEED/SEED_Tokenizer/train.py", line 16, in <module>
    import lavis.tasks as tasks
  File "/SEED/SEED_Tokenizer/lavis/__init__.py", line 15, in <module>
    from lavis.datasets.builders import *
  File "/SEED/SEED_Tokenizer/lavis/datasets/builders/__init__.py", line 15, in <module>
    from lavis.datasets.builders.image_text_pair_builder import (
  File "/SEED/SEED_Tokenizer/lavis/datasets/builders/image_text_pair_builder.py", line 16, in <module>
    from lavis.datasets.datasets.mmc4_dataset import MMC4Dataset
ModuleNotFoundError: No module named 'lavis.datasets.datasets.mmc4_dataset'
```

**Comment by geyuying** [comment]
You need to comment out the dataset builder that is not provided in this repo.
